"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.os3 = exports.sc3 = exports.HTMLMesh = exports.AnaglyphEffect = exports.OutlineEffect = exports.Redshift = exports.DepthLimBlur = exports.TriangleBlur = exports.FXAA = exports.AdaptiveToneMappingPass = exports.TAARenderPass = exports.ClearPass = exports.SavePass = exports.TexturePass = exports.UnrealBloomPass = exports.SSRPass = exports.SMAAPass = exports.SAOPass = exports.RenderPixelatedPass = exports.OutlinePass = exports.MaskPass = exports.LUTPass = exports.HalftonePass = exports.GlitchPass = exports.FilmPass = exports.DotScreenPass = exports.BokehPass = exports.BloomPass = exports.AfterimagePass = exports.RenderPass = exports.EffectComposer = void 0;
const THREE = require("three");
const EffectComposer_1 = require("three/examples/jsm/postprocessing/EffectComposer");
Object.defineProperty(exports, "EffectComposer", { enumerable: true, get: function () { return EffectComposer_1.EffectComposer; } });
const RenderPass_1 = require("three/examples/jsm/postprocessing/RenderPass");
Object.defineProperty(exports, "RenderPass", { enumerable: true, get: function () { return RenderPass_1.RenderPass; } });
const AfterimagePass_1 = require("three/examples/jsm/postprocessing/AfterimagePass");
Object.defineProperty(exports, "AfterimagePass", { enumerable: true, get: function () { return AfterimagePass_1.AfterimagePass; } });
const BloomPass_1 = require("three/examples/jsm/postprocessing/BloomPass");
Object.defineProperty(exports, "BloomPass", { enumerable: true, get: function () { return BloomPass_1.BloomPass; } });
const BokehPass_1 = require("three/examples/jsm/postprocessing/BokehPass");
Object.defineProperty(exports, "BokehPass", { enumerable: true, get: function () { return BokehPass_1.BokehPass; } });
const DotScreenPass_1 = require("three/examples/jsm/postprocessing/DotScreenPass");
Object.defineProperty(exports, "DotScreenPass", { enumerable: true, get: function () { return DotScreenPass_1.DotScreenPass; } });
const FilmPass_1 = require("three/examples/jsm/postprocessing/FilmPass");
Object.defineProperty(exports, "FilmPass", { enumerable: true, get: function () { return FilmPass_1.FilmPass; } });
const GlitchPass_1 = require("three/examples/jsm/postprocessing/GlitchPass");
Object.defineProperty(exports, "GlitchPass", { enumerable: true, get: function () { return GlitchPass_1.GlitchPass; } });
const HalftonePass_1 = require("three/examples/jsm/postprocessing/HalftonePass");
Object.defineProperty(exports, "HalftonePass", { enumerable: true, get: function () { return HalftonePass_1.HalftonePass; } });
const MaskPass_1 = require("three/examples/jsm/postprocessing/MaskPass");
Object.defineProperty(exports, "MaskPass", { enumerable: true, get: function () { return MaskPass_1.MaskPass; } });
const OutlinePass_1 = require("three/examples/jsm/postprocessing/OutlinePass");
Object.defineProperty(exports, "OutlinePass", { enumerable: true, get: function () { return OutlinePass_1.OutlinePass; } });
const RenderPixelatedPass_1 = require("three/examples/jsm/postprocessing/RenderPixelatedPass");
Object.defineProperty(exports, "RenderPixelatedPass", { enumerable: true, get: function () { return RenderPixelatedPass_1.RenderPixelatedPass; } });
const SAOPass_1 = require("three/examples/jsm/postprocessing/SAOPass");
Object.defineProperty(exports, "SAOPass", { enumerable: true, get: function () { return SAOPass_1.SAOPass; } });
const SMAAPass_1 = require("three/examples/jsm/postprocessing/SMAAPass");
Object.defineProperty(exports, "SMAAPass", { enumerable: true, get: function () { return SMAAPass_1.SMAAPass; } });
const SSRPass_1 = require("three/examples/jsm/postprocessing/SSRPass");
Object.defineProperty(exports, "SSRPass", { enumerable: true, get: function () { return SSRPass_1.SSRPass; } });
const UnrealBloomPass_1 = require("three/examples/jsm/postprocessing/UnrealBloomPass");
Object.defineProperty(exports, "UnrealBloomPass", { enumerable: true, get: function () { return UnrealBloomPass_1.UnrealBloomPass; } });
const TexturePass_1 = require("three/examples/jsm/postprocessing/TexturePass");
Object.defineProperty(exports, "TexturePass", { enumerable: true, get: function () { return TexturePass_1.TexturePass; } });
const SavePass_1 = require("three/examples/jsm/postprocessing/SavePass");
Object.defineProperty(exports, "SavePass", { enumerable: true, get: function () { return SavePass_1.SavePass; } });
const ClearPass_1 = require("three/examples/jsm/postprocessing/ClearPass");
Object.defineProperty(exports, "ClearPass", { enumerable: true, get: function () { return ClearPass_1.ClearPass; } });
const TAARenderPass_1 = require("three/examples/jsm/postprocessing/TAARenderPass");
Object.defineProperty(exports, "TAARenderPass", { enumerable: true, get: function () { return TAARenderPass_1.TAARenderPass; } });
const LUTPass_1 = require("three/examples/jsm/postprocessing/LUTPass");
Object.defineProperty(exports, "LUTPass", { enumerable: true, get: function () { return LUTPass_1.LUTPass; } });
const AdaptiveToneMappingPass_1 = require("three/examples/jsm/postprocessing/AdaptiveToneMappingPass");
Object.defineProperty(exports, "AdaptiveToneMappingPass", { enumerable: true, get: function () { return AdaptiveToneMappingPass_1.AdaptiveToneMappingPass; } });
const ShaderPass_1 = require("three/examples/jsm/postprocessing/ShaderPass");
const FXAAShader_1 = require("three/examples/jsm/shaders/FXAAShader");
const TriangleBlurShader_1 = require("three/examples/jsm/shaders/TriangleBlurShader");
const DepthLimitedBlurShader_1 = require("three/examples/jsm/shaders/DepthLimitedBlurShader");
const ColorifyShader_1 = require("three/examples/jsm/shaders/ColorifyShader");
const FXAA = new ShaderPass_1.ShaderPass(FXAAShader_1.FXAAShader);
exports.FXAA = FXAA;
const TriangleBlur = new ShaderPass_1.ShaderPass(TriangleBlurShader_1.TriangleBlurShader);
exports.TriangleBlur = TriangleBlur;
const DepthLimBlur = new ShaderPass_1.ShaderPass(DepthLimitedBlurShader_1.DepthLimitedBlurShader);
exports.DepthLimBlur = DepthLimBlur;
const Redshift = new ShaderPass_1.ShaderPass(ColorifyShader_1.ColorifyShader);
exports.Redshift = Redshift;
Redshift.uniforms['color'] = new THREE.Uniform(new THREE.Color(255, 0, 0));
const OutlineEffect_1 = require("three/examples/jsm/effects/OutlineEffect");
Object.defineProperty(exports, "OutlineEffect", { enumerable: true, get: function () { return OutlineEffect_1.OutlineEffect; } });
const AnaglyphEffect_1 = require("three/examples/jsm/effects/AnaglyphEffect");
Object.defineProperty(exports, "AnaglyphEffect", { enumerable: true, get: function () { return AnaglyphEffect_1.AnaglyphEffect; } });
const HTMLMesh_1 = require("three/examples/jsm/interactive/HTMLMesh");
Object.defineProperty(exports, "HTMLMesh", { enumerable: true, get: function () { return HTMLMesh_1.HTMLMesh; } });
const sc3 = require("three/examples/jsm/offscreen/scene");
exports.sc3 = sc3;
const os3 = require("three/examples/jsm/offscreen/offscreen");
exports.os3 = os3;
//# sourceMappingURL=PostProcessing.js.map